name: drf
version: '3.9'

services:
  web:
    container_name: web
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
